// Static code display strings — Python SDK and Supabase SQL schema

export const pythonScriptString = `#!/usr/bin/env python3
"""
Logos - Milestone 1 Content Generator Engine
This script takes raw text about philosophical/historical concepts and uses 
Google's Gemini API via the google-generativeai SDK to convert it into a highly 
structured, premium microlearning JSON pack ready for Supabase injection.

Prerequisites:
  pip install google-generativeai pydantic
"""

import os
import json
from typing import List
from pydantic import BaseModel, Field
import google.generativeai as genai

# Enable standard API client configuration
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY environment variable is missing. Set it first!")

genai.configure(api_key=api_key)

# 1. Structure Definitions using robust Pydantic Validation
class Card(BaseModel):
    explore_title: str = Field(description="Punchy, poetic, or dramatic title for this card (max 5 words).")
    explore_subtext: str = Field(description="Fascinating explanation or elaboration. Max 25 words.")

class ReadingPart(BaseModel):
    part_number: int = Field(description="Sequential number starting from 1 for deep dive reading.")
    text: str = Field(description="Continuous full essay narrative paragraph (70-130 words).")

class Presentation(BaseModel):
    title: str = Field(description="The formal essay title of the depth document.")
    reading_parts: List[ReadingPart] = Field(description="List of paragraph structures.")

class ContentStack(BaseModel):
    stack_id: str = Field(description="Lowercase snake_case ID (e.g. 'phi_marcus_01').")
    category: str = Field(description="Intellectual domain: 'philosophy', 'arts', 'literature', or 'architecture'.")
    topic: str = Field(description="Overarching theme title (e.g. 'Stoicism', 'Post-Impressionism').")
    philosopher: str = Field(description="Author key (e.g. 'Marcus Aurelius', 'Vincent van Gogh').")
    visual_mood: str = Field(description="Choice of setting: 'blinding_sunlight', 'cosmic_void', 'crimson_twilight', 'emerald_mist', or 'amber_glow'.")
    cards: List[Card] = Field(description="Exactly 4 sequential flashcards.")
    presentation: Presentation = Field(description="Detailed deep dive essay reading object.")

def generate_microlearning_stack(source_text: str) -> dict:
    # 2. Select optimized Gemini model
    model = genai.GenerativeModel("gemini-2.5-flash")
    
    prompt = f"Deconstruct and format the following material into a microlearning stack:\\n\\n{source_text}"
    
    # 3. Request strict JSON output conforming perfectly to Pydantic
    response = model.generate_content(
        prompt,
        generation_config=genai.GenerationConfig(
            response_mime_type="application/json",
            response_schema=ContentStack,
            temperature=0.4
        )
    )
    
    # Parse output to dictionary
    return json.loads(response.text)

if __name__ == "__main__":
    test_material = "Camus absurdism, the myth of Sisyphus..."
    data = generate_microlearning_stack(test_material)
    print(json.dumps(data, indent=2, ensure_ascii=False))
`;

export const supabaseSqlString = `-- SQL Schema to store generated stacks in Supabase database
-- Run this in your Supabase SQL Editor to prepare for Milestone 2 injection!

create table content_stacks (
  id bigint generated always as identity primary key,
  stack_id text not null unique,
  topic text not null,
  philosopher text not null,
  visual_mood text not null check (visual_mood in ('blinding_sunlight', 'cosmic_void', 'crimson_twilight', 'emerald_mist', 'amber_glow')),
  cards jsonb not null, -- Stores the array of 4 slides
  presentation jsonb not null, -- Stores the title and reading_parts
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index the snake_case handle for lighting-fast vertical feed fetching
create index idx_stacks_id on content_stacks(stack_id);

-- Insert live-generated content block generated by your custom configuration
insert into content_stacks (stack_id, topic, philosopher, visual_mood, cards, presentation) 
values (
  'phi_camus_01',
  'Philosophy of the Absurd',
  'Albert Camus',
  'blinding_sunlight',
  '[{"explore_title": "The Silence of the World", "explore_subtext": "The Absurd is born out of the clash between our desperate search for meaning and the silent universe."}]'::jsonb,
  '{"title": "The Myth of Sisyphus", "reading_parts": [{"part_number": 1, "text": "Albert Camus introduces the concept of the Absurd as an invitation to human lucidity in the face of modern existential disorientation..."}]}'::jsonb
);
`;
